name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore SimpleML.GeneticAlgorithm/SimpleML.GeneticAlgorithm.csproj
      - name: Build
        run: dotnet build SimpleML.GeneticAlgorithm/SimpleML.GeneticAlgorithm.csproj --no-restore -c Release
      - name: Pack
        run: dotnet pack SimpleML.GeneticAlgorithm/SimpleML.GeneticAlgorithm.csproj --no-build -c Release -o nupkgs
      - name: Login to NuGet
        uses: NuGet/login@v1
        with:
          usernameVar: NUGET_USER
          tokenVar: NUGET_TOKEN
      - name: Push to NuGet
        run: dotnet nuget push nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate
